version: '3.1'
services:
  angular_frontend:
    container_name: frontend
    build: ./frontend
    environment:
      - SHELTER_BASE_URL=http://localhost:8080
      - AUTHSERVER_BASE_URL=http://localhost:8081
    ports:
        - 80:80
    tty: true
    networks:
      project_network:
        ipv4_address: 172.10.10.2

  shelters_microservice:
    container_name: shelters_microservice
    build: ./shelters_microservice
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://172.10.10.100:5432/shelters
      - QUARKUS_DATASOURCE_USERNAME=postgres_shelters_demo
      - QUARKUS_DATASOURCE_PASSWORD=postgres_shelters_demo
      - QUARKUS_HTTP_CORS_ORIGINS=http://localhost
    restart: always
    ports:
        - 8080:8080
    tty: true
    networks:
      project_network:
        ipv4_address: 172.10.10.3

  authserver_microservice:
    container_name: authserver_microservice
    build: ./authserver
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://172.10.10.200:5432/users
      - QUARKUS_DATASOURCE_USERNAME=postgres_authserver_demo
      - QUARKUS_DATASOURCE_PASSWORD=postgres_authserver_demo
      - QUARKUS_HTTP_CORS_ORIGINS=http://localhost
    restart: always
    ports:
        - 8081:8080
    tty: true
    networks:
      project_network:
        ipv4_address: 172.10.10.4

  shelters_database:
    container_name: shelters_database
    image: postgres
    restart: always
    env_file:
      - ./databases/shelters_db.env
    volumes:
      - ./databases/shelters_dataset:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432
    tty: true
    networks:
      project_network:
        ipv4_address: 172.10.10.100

  authserver_database:
    container_name: authserver_database
    image: postgres
    restart: always
    env_file:
      - ./databases/authserver_db.env
    volumes:
      - ./databases/authserver_dataset:/docker-entrypoint-initdb.d
    ports:
      - 5434:5432
    tty: true
    networks:
      project_network:
        ipv4_address: 172.10.10.200

networks:
  project_network:
    driver: bridge
    name: pNetwork
    ipam:
      driver: default
      config:
        - subnet: 172.10.10.0/24